name: seafloor_geodesy_linux
channels:
  - defaults
  - conda-forge
dependencies: 
 # Python version & pip
  - python=3.11
  - pip

  # Code dependencies
  - bc # in linux but not mac?
  - scikit-sparse
  - sqlite # in linux but not mac?
  - tiledb
  - tiledb-py
  - scikit-learn

  # Build / compiler dependencies
  - setuptools
  - wheel
  - clang
  - gcc
  - gfortran
  - go
  - go-cgo
  - libstdcxx-ng
  - make
  - nodejs

  - pip:
    - -e .[notebook,dev]
    # - es-sfgtools
    - garpos @ git+https://github.com/EarthScope/garpos.git
variables:
  CGO_ENABLED: 1
  PIP_INDEX_URL: https://pypi.org/simple
