name: seafloor_geodesy_linux
channels:
  - defaults
  - conda-forge
dependencies: 
  - python=3.11
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - gfortran
  - julian
  - pandera=0.20.3
  - pyarrow
  - pydantic
  - pyproj
  - pymap3d
  - boto3
  - botocore
  - tqdm
  - nodejs
  - ipykernel
  - seaborn
  - sqlalchemy
  - sqlite=3.49.1
  - go
  - go-cgo 
  - gcc
  - make
  - tiledb=2.28
  - tiledb-py
  - libstdcxx-ng
  - clang
  - python-dotenv
  - scikit-sparse
  - sphinx
  - sphinx-rtd-theme
  - myst-parser
  - sphinxcontrib-apidoc
  - bc
  - pip:
    - -e .
    - -r pip_requirements.txt
variables:
  CGO_ENABLED: 1
