name: seafloor_geodesy_linux
channels:
  - defaults
  - conda-forge
dependencies: 
 # Python version & pip
  - python=3.11
  - pip

  # Code dependencies
  - bc=1.07.1  # in linux but not mac?
  - scikit-sparse=0.4.16
  - sqlite=3.49.1 # in linux but not mac?
  - tiledb=2.28
  - tiledb-py=0.34.2

  # Build / compiler dependencies
  - setuptools
  - wheel
  - clang=20.1.8
  - gcc=15.2.0
  - gfortran=15.2.0
  - go=1.22.9
  - go-cgo=1.11.3
  - libstdcxx-ng=15.2.0
  - make=4.2.1 
  - nodejs=24.10.0 

  - pip:
    - -e .[notebook,dev]
    # - es-sfgtools
    - garpos @ git+https://github.com/EarthScope/garpos.git
variables:
  CGO_ENABLED: 1
  PIP_INDEX_URL: https://pypi.org/simple
