name: seafloor_geodesy_linux
channels:
  - conda-forge
  - defaults
dependencies: 
 # Python version & pip
  - python=3.11
  - pip

  # Code dependencies
  - bc=1.07.1 # in linux but not mac?
  - scikit-sparse=0.4.16
  - sqlite=3.51.2 # in linux but not mac?
  - tiledb=2.28
  - tiledb-py=0.34.2
  - scikit-learn=1.8.0

  # Build / compiler dependencies
  - setuptools
  - wheel
  - clang=21.1.8
  - gcc=15.2.0
  - gfortran=15.2.0
  - go=1.25.7
  - go-cgo=1.25.7
  - libstdcxx-ng=15.2.0
  - make=4.4.1 
  - nodejs=25.2.1

  - pip:
    - -e .[notebook,dev]
    # - es-sfgtools
    - garpos @ git+https://github.com/EarthScope/garpos.git
variables:
  CGO_ENABLED: 1
  PIP_INDEX_URL: https://pypi.org/simple
