name: seafloor_geodesy_linux
channels:
  - defaults
  - conda-forge
dependencies: 
 # Python version & pip
  - python=3.11
  - pip

  # Code dependencies
  - bc=1.07.1  # in linux but not mac?
  - scikit-sparse=0.4.16
  - sqlite=3.49.1 # in linux but not mac?
  - tiledb=2.28
  - tiledb-py=0.34.2
  - scikit-learn==1.7.2

  # Build / compiler dependencies
  - setuptools
  - wheel
  - clang
  - gcc
  - gfortran
  - go
  - go-cgo
  - libstdcxx-ng
  - make
  - nodejs

  - pip:
    - -e .[notebook,dev]
    # - es-sfgtools
    - garpos @ git+https://github.com/EarthScope/garpos.git
variables:
  CGO_ENABLED: 1
  PIP_INDEX_URL: https://pypi.org/simple
