name: seafloor_geodesy_mac
channels:
  - defaults
  - conda-forge
dependencies: 
  # Python version & pip
  - python=3.11
  - pip

  # Code dependencies
  # - ipykernel # we need to make sure to build the notebook version to remove this
  - scikit-sparse=0.4.16
  - tiledb=2.28
  - tiledb-py=0.34.2

  # Build / compiler dependencies
  - clang=20.1.8
  - gfortran=15.2.0
  - go=1.22.9
  - go-cgo=1.11.3
  - make=4.2.1
  
  # Documentation dependencies (Optional)
  # - myst-parser
  # - sphinx
  # - sphinxcontrib-apidoc
  # - sphinx-rtd-theme

  - pip:
    - -e .
    #- es-sfgtools
    - garpos @ git+https://github.com/EarthScope/garpos.git
variables:
  CGO_ENABLED: 1
