name: seafloor_geodesy_mac
channels:
  - conda-forge
  - nodefaults
dependencies: 
  # Python version & pip
  - python=3.11
  - pip

  # Code dependencies
  - scikit-sparse
  - tiledb
  - tiledb-py
  - scikit-learn
  - pyarrow

  # Build / compiler dependencies
  - setuptools
  - wheel
  - clang
  - gfortran
  - go
  - go-cgo
  - make
  
  - pip:
    - -e .[notebook,dev]
    - garpos @ git+https://github.com/EarthScope/garpos.git
variables:
  CGO_ENABLED: 1
  PIP_INDEX_URL: https://pypi.org/simple