name: seafloor_geodesy_mac
channels:
  - defaults
  - conda-forge
dependencies: 
  # Python version & pip
  - python=3.11
  - pip

  # Code dependencies
  - scikit-sparse=0.4.16
  - tiledb=2.28
  - tiledb-py=0.34.2

  # Build / compiler dependencies
  - clang=18.1.8
  - gfortran=11.3.0
  - go=1.24.4
  - go-cgo=1.24.4
  - make=4.3
  
  - pip:
    - -e .[notebook,dev]
    #- es-sfgtools
    - garpos @ git+https://github.com/EarthScope/garpos.git
variables:
  CGO_ENABLED: 1
