name: seafloor_geodesy_mac
channels:
  - defaults
  - conda-forge
dependencies: 
  # Python version & pip
  - python=3.11
  - pip

  # Code dependencies
  - boto3
  - botocore
  - ipykernel
  - julian
  - matplotlib
  - numpy
  - pandera=0.20.3
  - pandas
  - pyarrow
  - pydantic=2.8.2
  - pymap3d
  - pyproj
  - python-dotenv
  - scipy
  - scikit-learn
  - scikit-sparse
  - seaborn
  - sqlalchemy
  - tiledb=2.28
  - tiledb-py
  - tqdm

  # Build / compiler dependencies
  - clang
  - gfortran
  - go
  - go-cgo 
  - make
  
  # Documentation dependencies (Optional)
  - myst-parser
  - sphinx
  - sphinxcontrib-apidoc
  - sphinx-rtd-theme

  - pip:
    - -e .
    #- es-sfgtools
    - garpos @ git+https://github.com/EarthScope/garpos.git
    - earthscope-sdk==1.1.0
    - earthscope-cli==1.0.1
    - sphinx_pyproject
    - gnatss
    - regex
    - cloudpathlib[s3]
variables:
  CGO_ENABLED: 1
